server:
  port: 8083
  servlet:
    context-path: /meep
meep:
  cron:
    expression: 0,30 * * ? * *
  pooling:
    configuration:
      endPointUrl: https://apidev.meep.me/tripplan/api/v1/routers/{$.country}/resources?lowerLeftLatLon={$.lowerLeft.latitude},{$.lowerLeft.longitude}&upperRightLatLon={$.upperRight.latitude},{$.upperRight.longitude}&companyZoneIds={$.companyZoneIds[*]}
      configurationZones:
        - 
          lowerLeft:
            latitude: 38.711046
            longitude: -9.160096
          upperRight:
            latitude: 38.739429
            longitude: -9.137115
          companyZoneIds: 545,467,473
          country: lisboa
          