spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:DB_INTERNAL_PROPERTIES_SQL;INIT=runscript from 'classpath:properties_inmutables/sql/create_tables.sql'
    driverClassName: org.h2.Driver
    username: meep
    password: meep

  jpa:
    show-sql: true
    
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE

          
          