spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dataBaseMeep
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG