CREATE TABLE MEEP_MOBILITY_RESOURCE(
	ID INT PRIMARY KEY, 
	EXTERNAL_ID VARCHAR(50),
	NAME VARCHAR(50),
	LONGITUDE DOUBLE,
	LATITUDE DOUBLE,
	LICENCE_PLATE VARCHAR(50),
	RANGE_VALUE DOUBLE,
	BATTERY_LEVEL DOUBLE,
	HELMETS DOUBLE,
	MODEL VARCHAR(50),
	RESOURCE_IMAGE_ID VARCHAR(50),
	REAL_TIME_DATA BOOLEAN,
	RESOURCE_TYPE VARCHAR(50),
	COMPANY_ZONE_ID DOUBLE
);



CREATE SEQUENCE MEEP_MOBILITY_RESOURCE_SEQ
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;
  
  